apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ivodocker-prod
  namespace: prod
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ivodocker
      env: prod
  template:
    metadata:
      labels:
        app: ivodocker
        env: prod
    spec:
      containers:
        - name: ivodocker
          image: paulohenriquejunio/ivodocker:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mysql-prod
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: rootUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: rootPassword
            - name: DB_NAME
              value: ivodb
  strategy:
    canary:
      # Service estável (versão atual)
      stableService: ivodocker-prod-stable
      # Service canary (nova versão)
      canaryService: ivodocker-prod-canary
      # Incrementos graduais do tráfego
      steps:
        # Passo 1: 20% do tráfego para canary
        - setWeight: 20
        # Pausa indefinida para análise manual
        - pause: {}
        # Passo 2: 40% do tráfego para canary
        - setWeight: 40
        - pause: { duration: 30s }
        # Passo 3: 60% do tráfego para canary
        - setWeight: 60
        - pause: { duration: 30s }
        # Passo 4: 80% do tráfego para canary
        - setWeight: 80
        - pause: { duration: 30s }
      # Passo final: 100% - promoção completa
      trafficRouting:
        # Para demonstração, usando apenas replicas (sem service mesh)
        # Em produção real, pode usar Istio, Nginx, etc.
        managedRoutes:
          - name: primary
