apiVersion: v1
kind: Service
metadata:
  name: ivodocker-prod-stable
  namespace: prod
spec:
  selector:
    app: ivodocker
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ivodocker-prod-canary
  namespace: prod
spec:
  selector:
    app: ivodocker
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ivodocker-prod
  namespace: prod
spec:
  selector:
    app: ivodocker
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
