apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivodocker-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PauloHenriqueJunio/ivodocker.git'
    path: helm/ivodocker-chart
    targetRevision: dev
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
