apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivodocker-dev-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/PauloHenriqueJunio/argocd-gitops.git"
    path: .
    targetRevision: main
    directory:
      include: "{rollout-dev.yaml,services-dev.yaml}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
