apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://mysql.github.io/mysql-operator/'
    targetRevision: 2.1.2
    chart: mysql-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mysql-operator 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 